### ISSUE TITLE
bring back executables?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/prolog-programming-task#1]
It looks like there isn’t currently an “executable endpoint” in this package that could be simply called via the command line. It existed, and was split off (https://github.com/owestphal/prolog/commit/8267db8b34e926527957d8c74a104674cc0086a3), then discarded at some point (https://github.com/owestphal/prolog/commit/e1132482c6a76a67c1369d78d7c2b180e7b8431c). Separately, for https://hackage.haskell.org/package/prolog-graph-lib an “executable endpoint” exists (https://hackage.haskell.org/package/prolog-graph) but hasn’t been maintained for a while.

**Edit:** By "this package" above, I actually meant https://github.com/owestphal/prolog. That is, I opened this issue in the wrong repo originally.

**Comment by jvoigtlaender** [comment]
Maybe "instead" (of executables in those "Prolog packages") there should be support here in the Prolog-Autotool-Task-Repo for running a task locally (taking all the configuration options from https://github.com/fmidue/prolog-programming-task/blob/2dea8782610c22da0d501cd2517cf387e98aa381/src/Prolog/Programming/Task.hs#L44-L82 into account).

Much in the spirit of https://github.com/fmidue/autotool-task-test for the Haskell-Autotool-Task.

**Comment by owestphal** [comment]
4d48a5a introduced a simple executable for locally running a task. This issue probably should have been closed back then.
Or do we need additional functionality from local testing?

**Comment by jvoigtlaender** [comment]
The functionalities mentioned in the first comment above are different ones, it seems:
1. Running the Prolog interpreter in an interactive mode.
2. Plotting (to disk) a derivation tree for given program and query.

It seems the 1. one is somehow covered by `app/Main.hs` in https://github.com/fmidue/prolog now? (Unclear whether it does more or less the same as what https://github.com/fmidue/prolog/blob/8267db8b34e926527957d8c74a104674cc0086a3/prolog-console/Console.hs once did.)

What about the 2. one?

**Comment by owestphal** [comment]
> It seems the 1. one is somehow covered by app/Main.hs in https://github.com/fmidue/prolog now? (Unclear whether it does more or less the same as what https://github.com/fmidue/prolog/blob/8267db8b34e926527957d8c74a104674cc0086a3/prolog-console/Console.hs once did.)

It does more than the old  `Console.hs` version. It can take a file as an optional parameter. The file's predicates are then usable in the interpreter (with live 'reloading' by parsing the file on every query).
It also supports primitive tracing (mainly for debugging the interpreter).

**Comment by owestphal** [comment]
> What about the 2. one?

The old executable works fine with the newer library and interpreter versions. We could either create a  new repo under `fmidue` for it or merge it back into `prolog-graph-lib`.

**Comment by owestphal** [comment]
fmidue/prolog-graph-lib@5c7a39654bc5e7bd29d0d358402f68aba293fa0b brings back the `prolog-graph` executable.
