### ISSUE TITLE
feedback on failed correspondence of new predicates

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/prolog-programming-task#16]
In an okay case, the deduced correspondence of predicates in the student solution to intended predicates from the task description is explicitly printed in full:

![image](https://github.com/user-attachments/assets/6189f29c-8f38-4d75-b958-3827d7b63d86)

But in a failing case, only a mismatched position is printed (and the mismatch is only reported implicitly via a reported disagreement in arity):

![image](https://github.com/user-attachments/assets/bc30122f-703b-4462-ace8-3f1baac8d6fd)

It would be more helpful if also in this case a printout of the whole mapping (possibly up to that point) were given. That is, the student would be told which of their predicates was taken for `Lehrer (1-stellig)`, which for `Zutritt zum Lehrerzimmer (1-stellig)` and which for `Zutritt zum Direktorat (1-stellig)`. Potentially only that information will actually help them understand why `zutritt_zum_lehrerzimmer` was interpreted as `X unterrichtet in Stufe Y (2-stellig)`. Ultimately, the real mistake in this case was *not* a wrong arity. It was a mismatch in which predicate is which.

**Comment by owestphal** [comment]
With the improved feedback the error message now looks like this:
```
Error while looking for required predicates.
Using the following definitions for required predicates:
- Lehrer (1-stellig): tobias
- Zutritt zum Lehrerzimmer (1-stellig): lukas
- Zutritt zum Direktorat (1-stellig): ben
- X unterrichtet in Stufe Y (2-stellig):
    Trying to use your defintion "zutritt_zum_lehrerzimmer" but the predicate does not have the correct arity.
    Expected a predicate with 2 arguments, but "zutritt_zum_lehrerzimmer" has 1.
- ist in der Schulleitung (1-stellig): zutritt_zum_direktorat
```
