### ISSUE TITLE
genauere Darstellung von "nicht erwarteten Erfolgsbäumen"?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/prolog-programming-task#2]
Hier: 
![image](https://user-images.githubusercontent.com/5853832/144806206-b45e6502-b2b6-492c-8b98-3062adeaaae0.png)
sind zwei Knoten rot. Aber aus völlig unterschiedlichen Gründen. Der linke ist rot, weil er ein Misserfolgsknoten ist. Das heißt, von dort ist kein Resolutionsschritt möglich. In diesem Sinne wird die Farbe Rot auch in anderen angezeigten Ableitungsbäumen verwendet (also insbesondere wenn eine Query, die eigentlich erfolgreich sein soll, doch keine Lösung finden lässt). Der oben rechte Knoten jedoch würde weitere Resolutionsschritte erlauben. Er ist wohl nur deshalb rot, weil weiter links ein grüner Knoten auftritt, also eine Lösung gefunden wurde, obwohl die Ursprungs-Query eigentlich nicht lösbar hätte sein sollen.

Es wäre unter Umständen besser, den rechten Knoten in einer dritten Farbe, zum Beispiel gelb, zu färben.

**Comment by owestphal** [comment]
Now looks like this 
![tree](https://github.com/fmidue/prolog-programming-task/assets/10613418/8bdb9a07-5917-48f3-a552-0f4f104b2ace)
