### ISSUE TITLE
Darstellung von Ableitungsbäumen näher an den Vorlesungen, parametrisiert

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/prolog-programming-task#3]
Studierende waren zum Beispiel verwirrt, dass der Prolog-Query-Prompt anders als in den Folien nicht mit angezeigt wird.

**Comment by jvoigtlaender** [comment]
Außerdem wären Kommas zwischen den Literalen nett, um etwa sowas zu vermeiden: 
![image](https://user-images.githubusercontent.com/5853832/145463091-6371ddbe-4dd5-4b8d-8d43-958ef65195cb.png)

**Comment by jvoigtlaender** [comment]
Mittlerweile gibt es hier noch mehr zu beachten als oben angemerkt, bzw. es müsste sogar eine Parametrisierung der Ausgabe der Bäume eingeführt werden.

Denn während die Anzeige in den ProPa-Folien so ist: 
![image](https://github.com/fmidue/prolog-programming-task/assets/5853832/2d532a05-9109-4889-aea3-2a7fa1b834e5)
und sie in den Logik-Folien auch mal so war, bzw. auch so: 
![image](https://github.com/fmidue/prolog-programming-task/assets/5853832/b572242b-0f53-444b-b9f1-de21478be03f)
ist sie in den Logik-Folien mittlerweile so: 
![image](https://github.com/fmidue/prolog-programming-task/assets/5853832/c57255f6-79dd-4958-bdc7-14458ca502af)
bzw. so: 
![image](https://github.com/fmidue/prolog-programming-task/assets/5853832/02412feb-58b0-4c03-813f-9fa733b1619e)

**Comment by owestphal** [comment]
Es gibt jetzt 2 Arten die Ableitungsbäume darstellen zu lassen:

1. Als Queries mit `Tree style: query` in config
![graph](https://github.com/fmidue/prolog-programming-task/assets/10613418/1cc25080-c260-40bd-8b69-c856e393ef4c)

2. Als Resolutionsbaum mit `Tree sytle: resolution`
![graph2](https://github.com/fmidue/prolog-programming-task/assets/10613418/4f57c04f-575c-4b4f-b728-2d04a0e88398)
