### ISSUE TITLE
"echte" anonyme Variablen in Feedback

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/prolog-programming-task#5]
Dies hat Verwirrungspotential:
<img width="488" alt="Bildschirmfoto 2021-12-27 um 13 37 26" src="https://user-images.githubusercontent.com/5853832/147472511-2bfd9a18-52ec-4461-8139-7ec28d4588bd.png">

**Comment by jvoigtlaender** [comment]
Weiterhin: https://autotool.fmi.uni-due.de/route/einsendung/129/133.

**Comment by owestphal** [comment]
Das scheint bereits in fmidue/prolog@d7cae59 behoben worden zu sein. Vermutlich wurde es aber erst verspätet ins Autotool deployed.
