### ISSUE TITLE
Constructor changes are not reflected on usage

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/prolog-programming-task#6]
The following changes are not covered by depending code (at least) in dependencies https://github.com/owestphal/prolog and prolog-graph-lib (currently hackage version):

https://github.com/owestphal/prolog/commit/fb9febe2ac23c0179bf44d47e8bda7bfdba237f6#diff-333d565c1d4e5176ad0fb3434c0f769a142ea4e22b98384b03238d94d466b314L20

https://github.com/owestphal/prolog/commit/fb9febe2ac23c0179bf44d47e8bda7bfdba237f6#diff-333d565c1d4e5176ad0fb3434c0f769a142ea4e22b98384b03238d94d466b314L32-R35

leading to errors in Autotool like
![image](https://user-images.githubusercontent.com/531939/148219435-e96f216a-9abb-4189-9a73-ad8432436ffe.png)
due to failing pattern match in:
https://github.com/mfourne/prolog-graph-lib/blob/61f58b73f313aea12507aed1481996358778554a/GraphViz.hs#L156

Probably further places like
https://github.com/owestphal/prolog/blob/c339040625cb300c7682acb660c4288e3aed0b31/bench/Main.hs#L15-L16
require amendment.

**Comment by owestphal** [comment]
fixed for `prolog-graph-lib` in fmidue/prolog-graph-lib@4dbc1f2a96ab9adb3cadbecb769e60828c45c4a2

**Comment by owestphal** [comment]
also fmidue/prolog@2ba8d11a50e8977829f3222411693bc653e68be5

**Comment by marcellussiegburg** [comment]
The provided changes seem to fix the issue. There is no reference to the original task instance/submission in order to test the exact spotted error case scenario. If the error should reoccur it would probably be best to open a new issue.

**Comment by jvoigtlaender** [comment]
> There is no reference to the original task instance/submission in order to test the exact spotted error case scenario. 

Here is an instance from last December: https://autotool.fmi.uni-due.de/route/einsendung/389/913
